apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: pv-pvc-manager
rules:
- apiGroups: [""]
  resources: ["persistentvolumes", "persistentvolumeclaims"]
  verbs: ["create", "delete", "patch", "update", "get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pv-pvc-manager-binding
subjects:
- kind: User
  name: <username>
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: pv-pvc-manager
  apiGroup: rbac.authorization.k8s.io
